FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/redirect ./cmd/redirect

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/redirect /app/redirect
EXPOSE 8081
CMD ["/app/redirect"]
