FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod ./
COPY . ./
RUN go mod download
RUN CGO_ENABLED=0 go build -o /out/storage ./cmd/storage

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/storage /app/storage
EXPOSE 8082
CMD ["/app/storage"]
